A AC A
B A AC A
A
AC A A AC
A BC C A AA BA BC CB A AA 
A AA AA AA A CA CB BA BA A 
C B BB AC B C A A A BB 
C AA C B C A BA A BA AC 
BA B B BA AB B CC C C B 
B B AC AB A BC A AC
A B CB AC C 
CC C A B CC B AA AA CA AC 
B BA A B BC A AC
A AA AA AB C A 
AB CB BA B C B AC A
AC A CB AB BA 
CB A C BC C B CA B C BB 
A A AC
A AA BB C C A AC
A A AC CC B CC 
A C A BC CA CB CC BB BC C 
A CA B C C BC A AA CC B 
AB B C BC B BB A AC A
BA BA BA C 
B BC C C B B B AC A AC
A B CC 
B C BC CA C A
AC A CA C A AC
A BC C AA 
A BB AB A BA AC CC C AA BC 
CA AA AC CB CA B AC AB CB A AC
A C 
BB AA BC A B BB B C AC BA 
BB C A AA C CB A
AC A A AC
A AA B BB BC 
AC CA AA C B C C A C B 
A B C A C AA A A
AC A BB BA CC 
B CA A AC A
C A AB CC AB C BC CC 
B A AC
A BA B CA AA C C CC AA BB 
CC CA A AB AB AA BC B BA A 
A AA CC A
AC A C CB CB B A C A 
AC A
AC A B A C BB AC A A B C 
B A AC
A A CC BA B CA A AC A
B A BB BC 
C CA BA C CB C A B C B 
CA B B CB B CA AB C CB C 
A A AC A
A C B AC A B A BA AC 
CC BB A CA C BA B BC AC AA 
A
AC A AB BB A A
AC A CA CB AA B AC AB CA 
B CC AC AC B CC C A AC A
AC CA CC 
CB C BC CB BA CA AC CC BA B 
A AB B BC B CA C BA CA B 
CA A AC A
AA C B CB CA CC B B A 
B A AC A
BB C A CA CB B B A AC A
AC AA 
C A CC CA A BC A CC BA A 
BC BA B CA B A CA A AC A
C C A 
AC A AC A
A
AC A CA BA CC AB CB A AC
A CC AA AB A AC A
B 
A BA A AA A CC A AB B A 
B B A C CB A C CA AA C 
AB A CC A AC
A A B C BC C C AC 
BA C A C CA BC BC AC A B 
C C B C BB CA BC AB BB CC 
C C CC B A C CA AC B A 
BB BC AC AB AC BA AC C A AC A
CB C 
A A AC
A C BA CC A A AA CC A A 
A A AC
A CA A B A CC B B A A 
AC A CA CC B B CA BB C B 
CA AB BA CA BA A BC AC C AA 
A C BA BA AC C A
AC A AB CC BB B 
AA B BC A
AC A CA BA BC B B AB CA 
BB A
AC A A CA BC C A AB C B AC 
C BB A BA C A BC B A BB 
BA A AC
A BC B BA CC B CB C A A 
B CA B B CB C B AB B A 
BB AC C B CB AC BA AC A A AC A
A 
C C AC AC BC C B BA C A 
AB A AC
A AC CC AB C B B CA BA AC 
BB BA A AC
A B B CB CC A C B B 
C BC A B B CC AB B CB CC 
B CC CB BA BB B B A AC
A BA CC A 
C B AA BA CC A B C C CA 
CA A AB CB CA CC C B AA BB 
BA A AC
A A CB BC A BA B CA BC CA 
BC CA CA A
AC A CA A A A AC A
AB A
AC A A CC AC 
CC B B A C A CA A AC A
AB AC CA 
C A CA B BB AC A B CB B 
CA A AC A
A AC
A C AA B A AC
A AA A BA B B AC 
C BA CB A BB CA CC B BB CA 
B A AC
A B AA A AA BB C B C A AC
A BB 
BA B C BA AC BA AB B A CC 
CA A CA C A B BA B CA CA 
AA C B A A AC BC A
AC A CB C CB 
A B AB A AC AA AB B AC CB 
C A CB CB B CB CB B C CA 
A A AC A
C C B CB BA AB C C C 
A A C A B B CB CA A A
AC A B 
C A CC AC C C AB A AC
A A AC AB 
C AA AA B B A B B A BC 
A
AC A B CB BC B C AC CA BC B BB 
CA BC A AC C B B A
AC A C AB CC 
B A AC
A CB C CC AB C AA C B B 
B B AB B A B AA C CC CB 
AB A
AC A C CA BA BA BC C CA A A 
C CC A A C A AB B BB BA 
A A A C C A
AC A B A AC CC A 
B BB A CB B AA C C A
AC A AC A 
A A AC
A C BA A
AC A AA CB AC C AC CA C 
BB A C CA B A CA B BB B 
B CB C BA B BA BB B CA AB 
CA A AC
A B BB AB C A B A B B 
BC C C A C C AB A AC
A CC CC C 
B A AC A
CA CB AA BB C CA AB A
AC A CB BC 
CC A
AC A BA AB CC A CB AC A AC
A A C BB 
A
AC A CA CA BB CC AA B C BC BB CB 
CB A
AC A AC AB C AC AB A A C A 
B A AC A
CA B BB CB A CA A AB CA 
AB B CC A B B A A CC A AC
A CA 
CC BA AA A AC
A CA CB A AC
A BA A
AC A A BA CB BC 
B A
AC A A AC
A C A BA AA B B BA C BA 
C A AA CA BA AA BA BA B C 
BA CC A BC C B A
AC A BC C C C 
A A B CC CA C C AC A C 
C A AC A
AB BC A AA B AB AC AC A AC A
A 
C A AB AA CC A AC AA B B 
A AC A
A A AA B BB A AC BA A C 
BB BA BB AC C C AA CA AC A 
B BA B AA CC A AC A
CB BA A C B 
AC A AC A
B CA C C BB AB AB CA AC 
CC BB AC A AC
A CB A BA A C C A 
A B C AC CA B BB C AA CA 
A AB BC A AC A A B AC A AC A
B 
CC CA C A AC
A B CB AC A C A AC A
B A 
C BB BA AA C CC B B AC B 
CC A AB A AB B A CA AB B 
AA A BC C CA BA A AC
A BC A CC A 
A AA CC C C BA CA B C BC 
AB A AC A
CC BB BC A A BA C B AB 
B A C B A CB AC AA A A 
CC A AC A
AB BB CC BB CA B CB C BA 
AB CB B BB BB C CA C BC C 
C CA B C BC CA BA C B A AC
A C 
BC C CA B AA BC BC AC C BC 
A A AC A
C A
AC A BB A B AB AC B BB CA 
B B A AC C B A CB B CA 
A BB A CC AC A B A A
AC A C C 
BC BC CB BC BC BB C A A B 
BC C CB C BA A B A AC A 
A AC A
A BC CC A AC
A CB CC A B A C C 
C BC A C CA CB CA AB AC A 
AA A AC
A AA A AA B B C CB AC B 
C A C A
AC A BC C C CC B C A 
C CA C BB B AA A B AC A 
A C CC B B CA A
AC A CC CB AB AA 
B AC AB B A B BA BC CC C 
BB CB B CB CC C CC B C AC 
BA BB AC A
AC A BB CC A C A CC A 
C AB BC A AA BA C BB B A 
A BA AB C CB B A C B B 
AA A
AC A BC AA CB BB CA B AC CC A 
C B CB C BB AA CC AC B C 
A A
AC A B BB AB A A AC
A AC AB AA BA CA 
A AC A
A AB AA C BA C B A BA C 
BA CB AC C A A AC
A AB BA B AC AC 
CC B B A AC
A CC AB AA C CC AB BC 
AA A
AC A CB BB C A AC CA A AB C 
C C C AB C C B BC A A 
A A AC A
A AC
A CB CB A AC BC A
AC A CB BB A A 
A BB B A C B C B C C 
CA AA C B C BA AA C BC B 
AC B C B BB C A B AC AC 
A AC
A AA A
AC A A BA BB A BB B A B B 
CB AC A BC A B AB AA B BC 
CC C A AA A A CC B A A 
A A AC
A C BA A BC AC BB AC B B 
A C B A C A C A BA AB 
A B B AC CA C A A AC
A C CA A AC
A C 
B C CA A A B CC CA B BA 
CC C AC B AB A C C BB B 
CA B AA CB BA B CB C CC A 
A A C A AC A
BB B B BA A C C 
BA A AC A CA A AC A
A CB C CC B 
AB BC BA C BA B CA CC C CC 
A BA B CC AC A B A
AC A A AC BB 
BA AC B A BA A AB AA BA B 
B A AC A
AC B CB A C CC AA AC BB 
BC B C A
AC A C B C C AA C A 
B A AC A
A B BC CB BA A A C A 
A A A BC AC AC C A
AC A B A
AC A B C 
A AC B A AC A
AC C C A AC
A CB AB B B 
AC A A AB A A B C AA B 
CB A AC
A BA C A AC
A CA AB CB BA BB A AA 
A
AC A AA A BA A AC
A BA AC B BA BA AB BC 
BB A CB A BB C CC B C BA 
B C A AC BA CC B C B CA 
BA C AB A AC A
A
AC A A AC
A A A B BC CA C B 
BA CC CC A AC
A AB BC A
AC A A CA B AA AB 
A A AC A
C CB A C C B A AC
A BC B C 
B C A BB C A AC AA B C 
B A AC
A A B B A CA AB A
AC A B AC CB 
AB AC AA B A CB AA A
AC A A AA CB 
B BA BA BA B AB A
AC A B CC B CC 
B BC CB BB BA BA B C CC A 
CC A C AA A B CC BC C AA 
C A A AA AA BB BB A
AC A AB AC B 
A C C BB AB AC AC C A C 
B A
AC A A AC
A A CA BA C B B B AC BB 
AA A AC A
BA BB CC CA B C A BB BB 
B B BA AC B A AC A
A B BC B AA 
C BA AC CA A B B C C B 
CB C CC AB A AC A AC
A BC CA A C 
BC CC B CB A CC C AC A CC 
BB B AB A BB AC C AC A C 
AA BC CA BB AA CA B C AA CA 
CA AB CB A AC A
A
AC A B A AA CB C A C 
CC A AC
A B AC C AC B B A B B 
A
AC A A C C A AA CB A AC
A AB B B A 
BA A AC
A BC B C AC C BA B B CB 
A CA BA BC C B AC A AC
A C A BA 
A BC BB C C AC B C AC BA 
CB CC A B A CB AB A CC AA 
AB B C B B BA B B A AC
A AB AA 
CA AB B CB B B CA BC AA C 
A C B AC A AB B BA C B 
C B AC BA BC AC B C B C 
C B AA A CB AC C B A CC 
A B C A BA AC CA AB A CB 
B B AA CC A B AA AA CC C 
CB AB C B AA C C C AB B 
A B AB B BC A CB C C AC 
CC A AC A
AB A CA CC C A A C C 
C AB A AB CC AB C CA BA A 
CA B BB AC B B AA C C CA 
AC A
AC A AC CA AA C C C AC C A 
BC C C CC A AA C C AC A AC
A CB 
BA BA B CA AC BA CB B A B 
A CC BB A B B B AA CA C 
B CC A BB AA AB B AB C AA 
B A AC A
CB A A C C C A C A 
C BA BA B A
AC A B B CA CA C C 
AA C A A A C A A CA B 
A CB B C A A CA CB C AA 
A AB BB BB BA AA AB A AC
A AB BB AB 
AA AC BA AC A AB C AC B BB 
C AA C A
AC A A AC
A C BA B C CC BA A AC A
A 
CC A
AC A BC A B A C CA BC C A AC A
A
AC A BA 
BC A CB C A AA A AC BB B 
BB AC BC CC CA CA CC BB B AB 
CB BA CC A CA CC B C CA AA 
A C CA CC B A A AC
A CA A B C 
A CC BC AB B BA AB A A AC A
AC A 
C A AC
A A C AB B B CC C AB BB 
C B B A BC A AC
A CA BC BB AB BB 
B A AA CB AB A C AC BC C 
BB BA CB B BA B A AC
A A A AC
A B BC A 
C BA AA B CA C B C A AC A
CA C 
AA AC C BA BC A AA A AC CC 
B A CA C C BC CA CC B B 
C CB BC A AC C C C C A AC A
AB 
AC C C C B B AA CC B C 
A A AC
A BC C A
AC A AA BA B BA A B A 
AA CC CC A AC A
CB C C A A BA AC 
A C A BC B B CA A A
AC A A AC
A CC A 
CA A AC
A C BA A C C A AC A
AC B B A 
C AB CB C A BB A
AC A B BB AC A 
CB BC BA C AC BA C BA A B 
CB BA BC CB CB AB A C BB CC 
CA AA C A B A A B B A 
B AB BB A BB A C CB AA AC 
AB AB A A BA AC CA BA A A 
AC CB CB BA CB A C BA AC BC 
AA C B C A AC AB BC C A AC A
C 
AB B C C B C A A BB B 
A A AC A
A AC
A BC BA AA B BB AB BB CB CB 
CA C BA CB A BA A A
AC A BB BA BC 
C A AB BC B C CC CC A CB 
A BA A A
AC A C B A CB AB B CA 
C BB C BA CC C C B AC BB 
C A AC A
BC A CB B C B BC C A
AC A CB 
A AC C CC A AC A
A A AC
A AB C AA AA CC 
B BA CA BC AC CC C C C B 
CB A
AC A AC B AC BC CA B AB AC AA 
BC BC A C AC B CA AC CC BC 
CB A AC A
C AB B B CC BB CB BC CB 
A B CA CB A
AC A A AC
A CB CB C B C CC 
A AC A
B BC C B CC AB AA BB A BA 
C CC BA BB AB A B B BA BC 
A B C BB C AA A A
AC A A A AB 
CB CC C C BB CB A A C B 
B BB B AC CB BA BB B A AA 
B A
AC A BA CB BA CB B B AA A BC 
A B B B C CC AA CB A C 
C AA CA AB B A AC A
A CC A
AC A BA BA A 
C AC BC BB AC AB AB CA B C 
AC B A B B C CB A CC C 
C BC BC AA A B AC B A AA 
AC C A C C CC BA B BA C 
BB A
AC A C A A CA B B B C A AC A
A
AC A BB 
BC CA CA C CA BA B C CC AB 
AA A
AC A CC C CB BB C CC BB BB CB 
C B A BC BA CA A AA BB A AC
A AB 
C BB B CC CB A C B BA AC 
BB C B A
AC A B B AC C A AC
A C A A 
C B BA C A C AA CC BC BA 
A CB CC AB CC A BA BA BA B 
AC A AC A
A
AC A A AB B C B C CC C BB 
AC C A B B C B B A B 
A A AC
A C C B CA A
AC A C C B CC BC 
C C C BB B B AB C A B 
AC BB BB B B B A AC
A B A
AC A CC B AC 
AC AC AC A C BB BA BA AB A AC A
B 
C CB B C C AC C CA BA B 
C A AC A
B AA A AC
A B B BB BB BB BC A AC
A AC 
A AC AB A C CA B B A CC 
CC A AC
A B CC AC BC B CB A AC A
A
AC A BC BB AC 
B A AC A
B A B A
AC A CC CC A B A BA 
AB A AC
A C AB A C C C BB AB BB 
AB A AC A
A
AC A BA B CB AC A C A C AA 
B B B CC AA B BC A B A 
BB A CB B BB B C A AC
A B AA AC 
BC B A CC A B B B C BB 
C C B AA CB A BB BC BC A 
BA A A A C BB CB C BC BA 
CA A
AC A A AA C CA C B A BA BA 
A AC
A B A BC AB CB C A BC BC A
AC A C 
B A AC A
C C B B BA AC AB AC BA 
C C B BB C BA AC A AC A
CB CA BC 
BB B BC C AB AB A AA B BC 
BC CC C BA CC B B C BC C 
B A AC A
AC CB B A C BA B AA B 
AB CB BB C AA A C A AC A
A AB A 
C C AB C AB A A AA C C 
BB A
AC A A AC
A B B C AA C B BC A C 
C BB CC AB CB BB A A BC B 
BB CC AA BA CB A C A B AA 
BB CA BA A B AC B AB B C 
CB CA B CA CC AB A CC C C 
AC C AC A BB CB B B CC CA 
B AC A CB BA BB B A AC A
B BA A 
A CA BC C BA A
AC A C C B A C 
BA A
AC A B A C B A AC A
A B B CC CB 
A BC AB AB CC BB BC B BC A 
A A AC
A B BA B C C CB BA AC A
AC A A 
C CC AB CB AA AB CB C B BC 
A A C BB C BC B A AC A
CB AB A AC A
A 
A A AC
A B CB A BA CB BB A BC C 
CB CC AB AA BC C AA CA CC A 
AC C A A BB A BC A AC A
CA BB C 
B C CC CB CC CB AA B B B 
B A B CC B C C B A B 
BA BC B A A
AC A BA C BA A BC A 
C A AC
A A AA C A A AC
A BC A CB B A 
BC AB A BC AA A AA B CC A AC
A C 
BA C CA C A C B AA C B 
A CC B B BA A A C C CB 
AA A AC A
A C A AB AA B AC A A AC A
A 
A A AC A
CC C A CC A B A AC A
CC B AA 
C A A AC
A AA B C A AC
A BC BA CB CA A 
CA A AC
A A AB CB B BB AB B A CB 
AB BA B CA C CA CB CA A BB 
C A CC AB C A CB C CB B 
BC BB A B BC A AC A
B A B B AA 
C BA AA AA A C CC A
AC A CA AA C 
B AA AB BC C B A
AC A B C C BB 
CC B BB A AC
A B B BA BB AB B CB 
C A AC A AB C A AC
A A BA CB A 
A BB CB AA B B B CC CC C 
C CC B C BA BA CC AC BA BC 
A A AC
A C AC CC AC A A AC
A CB B CB AB 
BB A AC A
A
AC A AA C A CB C BB BA C AC 
C A AC CC BA AB C A
AC A A AC
A AB BC A 
C CB A A A B BC AB AA B 
AC A
AC A B AB CB B B AB BC C A 
A A AC A
A B CB A A CC A AA BA 
BC B C B C AA BC AB B A 
A A C B AB A CA B CA A AC A
BC 
AB AC C C C AC C B BA CB 
BA C B CB C BB C C BA CB 
AC B AC C C CB C A A A
AC A CC 
A AC
A C A AB CC CA C A BB A AC
A B A 
CC AC B BB B C B C AB BA 
AB A
AC A A AC
A A A AC A
B B A A BB B B A AC A
B 
B B A BC BA BB A B A AC
A C B 
BA BC AA CC AA AC AB B CB C 
AA A C C C B AC C BA BA 
B A AC
A C B BB A AC A
A AB B CB BB CA 
A B B A
AC A BA AC AC C A AC A
A AC
A B C A 
B B A CB C CA BA C A C 
BA A AC A
BB CC A AB C A A CA CC 
A A AC A
A CC AB A
AC A B BC A C BB A 
BC BA A AB AC B B AA AB B 
A C CB AB C A B BA AC A 
BA C BA C BA CB CA B CC B 
CA BA AB AA BB C AA AB BC C 
BA CC BC CC A AA AA B BB B 
C BC CA AA CC A AC A
B CB C CC B 
B CB CA BA B B A AC A
C CA CA C 
A A
AC A A AC
A C BA AA A B AC BB B BA 
CC CA BB CA AC A A C A CC 
C CB AA BC BC A BB C AC A AC A
B 
CC CA C BA AC A C A C AA 
CB C A A A A C BB C C 
C C CC BA AB A B BB C AC 
AC A AC
A AC AB C CC A CC B BA CB 
B BA A AC A
A B BC BB B BA C B 
B CA B CB BB AB A CB C B 
B AA A AB AB A
AC A C C CB AA BB 
C A AC A
A CA A B BB AB CB C BC 
CC B C B A AC B B BC C 
CC A C CA A CA A AA AA A 
B A BA BB C C B BC CA BC 
C C AA B BA C BA CA BA C 
C A AC A
B CC A AC A
BC B B BA C C A 
A AC A
C AC C A
AC A AA BB CB A CA AB CB 
A AC A
CC A A AC A
C CA A CC A CC AC A 
C B BC B A A AC
A C C A BB CB 
A A
AC A A BC C CB A AC A
AC A B AB CA 
BC A
AC A A AC
A BC B A AC A
AA AB C AA BC A AA 
C A B AB AC AA AB BA C BA 
AC C B B A C C C A A AC A
B 
CC AB A A
AC A A AC
A A B AA BA BA A BC 
A B BC C AA CC AA BB A B 
AA AA C AB AC CB B C B C 
AB A A BB A CC B A AC
A C A A AC
A AC 
A C AB B BB BC AB C AA C 
CC A AC
A CA AB B AA B AC AA BA AA 
A B A AA BA A CB C A B 
BB BC BA AC CC A CB B CC BC 
AA AC A CB CC BA AB A AC
A A B CB 
C A C CA CB AC CB C AC AB 
CB A AC
A AC BC C A B A A AC
A C AA CA 
A AA A AC
A AC BA CB A A C B A 
A CA A BA AC BC CB BA CA B 
BC C B AB C B A A AC AA 
CC BC C AC A AC
A AA AC BC A B BB 
BC CC BC B AC CA B A AC A
CA A
AC A BB AB 
C BB AB BC A A C BB CC CC 
AC CC A BC B BA B AB AC CC 
A B AA A AC
A AC C A AC
A BB B AC A A 
CC C AB BA B AB A CA A A 
A B CC BC AB C A AC A
CB B A A 
B BA A AB B BC C B B AC 
CB CA B B A A BC C A AC
A BA BA 
B A BA B CB A AC A
B BC B AB CA 
C CC CC B B A A AC
A A B AB C 
A C A AC B B C AA A CC 
B BB BA BA BC BB C C A BB 
C AB A B A BB CC BC CC CC 
CA AA C AB CC A C AA CB C 
A A CC BB B B BB C CB AB 
AB BC B A AC
A B CC A C A C BA 
C C B C A B AC CB B CB 
BB CB AA A CB B C A AC A
CA AA B 
C B B A BC C CA A AC
A B AA A
AC A B 
AA AB B B C A A A B CC 
CB BA C C A B B AB AC BA 
B B BA A AC
A A C C AC A C BA 
CB A
AC A BC AB CC C BA CC B C BC 
B A C CB CA CB BC A
AC A CB A AC 
A C A AB A CC AA B B A
AC A A AC
A CA 
A A BB A BC BB CC CC A AC
A CB B 
A B AA B BC C B CA AA BA 
AA B CB BA CA AA A AC
A B AA AB C 
BC BC CA AC A BC A A A C 
CB B C CA A AC
A B A A BB B CA 
BB B C B CC B A C B C 
C AC AB AA C BC AA AB CA CB 
BA B B CC BB A BC A B AA 
AB BA BB A AC A
CA CC C C A C BC 
A C CB AC CB A
AC A CB A BB AC CC 
B CA BC A C C A A AC
A AB A AC A
A CA 
CA A CB AC BA BC AC B CA C 
A B A BA B A AC A
A C AA CB A AC A
AA 
BC A
AC A AC C BB BC B A
AC A BC AC B C 
CA A B A CC A A
AC A A AC AC CC 
B AC CA B B BA CA A A AB 
C A
AC A A BA CB BA BC AB A
AC A A A AC 
C C B AC BB CC A A
AC A A A A 
BC AA B B BB C C AA CA AA 
B AB BC BB CB A A AC A
A BC A C 
A CB BC CA A BC BB BB CA C 
CB B B AC AB B C CA BA A 
BC AA AA BC BC A CA C BA AB 
AA C B CC B CC A A CA B 
C A AA C B AB A AC
A AB A CC A 
B A AC
A C BC BA BA A A A BA BC 
AA A A B B BA BA AC A AC
A BA CC 
CB C BC C BC A
AC A A AC
A B BA AB B BC 
A A AA C CC B CA B A BB 
C A AC
A B A C B C AB CA A A AC A
CC 
A C A
AC A CA A CA AA A CC BA CB 
C C A BB C C A AC
A AA A
AC A C CB A 
CC C B B AC B B B BB CB 
BB A AC A
C AC AB CC AC C C B A
AC A C 
AB C AC AB AA C A AB C C 
B AC AB A A A AC A
C AC C C BA 
A AB CA CB AC A B BA C C 
A B BB A C C AB CB BB CC 
CA A C AB CB C AC BB C AA 
C A C C A AC A
AA AB CA B B A
AC A C 
AB AB C CA CB A C A AC A
CC CC AB 
CA BB CA CB A BB C B BC BB 
B A
AC A C B AA A B AA BB CA C 
B B BC B BB B C B B B 
AA A C B CB CC A AC A
CC A BC A 
C AA BC A C B CB C BC A AC A
A 
B C C BB C BB B BB A A 
BA A AC
A BA BA BC C C A CA B C 
C C B B B A CC A A AB 
BC B CB A
AC A C AC BC A AC C A
AC A A AC
A BB 
C B B AB CA B A B CC C 
AB A
AC A C A A B A A
AC A AC A A AC 
AB A BB C BB B AA A AC A
B B AB 
A A
AC A BB C C AB AB CB AB AB A 
CB CA A A AC A
A AC A BC BC CA BC 
C A CC A AB A CC AA B C 
A AA AA CB CB B C C BA A AC
A C 
CB AC B A A C CB AA AC B 
C A CA BC A AB A A AC
A B A AA 
AA CC C CC B B B A CA B 
B BC A AC A
C BC A C AA C A C 
BC CB A B CB A AC A
AA BB CB BA A 
BA C BB C B B CC A AC A
C A BB 
CA B B B CA CA B BB AB CA 
BB BB A BA A C BA A AC
A BB B AA 
B CA AA BC A A
AC A B A AC
A CB CB A C 
CC AA A A AC
A C CA BA BA A AC A
A
AC A AB AA AB 
B A
AC A AA AB B A
AC A CA C C B C B 
A AC
A CB AC B A AC
A BB BA A A
AC A CB B B B 
CC AA AB C C C AC AC C CB 
C CC C C C A AC B AB CA 
C BC A AC
A B BB B B C A A AA 
AC BB A C A A C CB A
AC A A B 
AB A C A B AC B CB A A 
B BA CB C BC AA AC B BC B 
A A A A A A AC A
A B AC A AA 
B BC AB BB C B B AB B B 
C B BC C BB C C C AC A AC
A B 
B AC AC C CA AC C C CC CB 
CC BB BA BA C CB B A AC
A BC BC CB 
BC AA C AB C BA C CB CB BC 
BA C AB C B AA CB CA BA B 
AC A B C CB A AB BB A B 
A C B C A BB A AB BB B 
A AB A B BC A AA AA CA A 
CC A
AC A A AC
A CC AC B CC C AC A B AB 
A AC B A
AC A B BA B BB CB BA CA 
AC A AC A
C A
AC A AA B BC C CC B C AC 
AC BA BC B C CB B B AC BC 
C A
AC A C B AB BA BA AC B AB CA 
B A
AC A C AB AA A CA BC A C CB 
C BA C C B B C AA B AC 
BB C C B AC BB AC BC C AA 
C AB B A CA BC AC C AC BC 
B B AC A
AC A C CA BA B C CB C 
B CC B A AC A
A AC BB AA A BC CB 
BC B C A C B C AC A AC 
CB B A
AC A C BC B B BB CB B C 
A C BA B B C CB A AA A AC
A BC 
AC AB C CC C A CC CC C AA 
BC A C AB BC BA B A CC BC 
C A CC AB AB BC A BC A AC A
BC BA 
A AC CB CC BA B BB B C A 
B A AC
A CA C B CC AC CA A CA B 
AA B B AA C A AA AA AB A 
A AC AB A AA B B C C CC 
B A B C CC BA A AA B BC 
AB A AC A
B BC CA AC CA C AA BC A
AC A A AC
A B 
BA A
AC A BC A BB A A BA BA C CB 
B A AC
A BB C AB BA CC CC BB AA B 
B CC B A CC BA AA B AC BB 
CC A AC
A B CC A AC A AC
A CA BC BB CA A AC A
AC 
CB C B B CA B B AA B B 
CC AB A
AC A BC A B A C CA AB CA 
BA A C BB CA CA A
AC A CC AA A AC A
AB A 
AB AA B CA BC AB B C BB CB 
A AC
A C CA C AC B B BC A CA B 
C A AC A
C AC CA B A AB BA CC BA 
BC B CB C CC AC AB AC BC CC 
AB BA CA CC C BA BC B A
AC A AA C 
AB CB AB B CC A B C AB C 
AB A BC A B C C CA B B 
A A B C BC CC AB AA AA AA 
BC CA B A CB BA A CB C C 
B A AC
A B AC B B AC CA AB BB B 
B CC BC BB B BA C B CC CC 
AB BC AA B B BB CB C AA AA 
CC A
AC A CA BB AB CC C AC AC BB BC 
CA C B BA B AB CA B C B 
A A B C AA A AC A
CC AB A A A AC A
A 
AA AC BB CA AB B AC BA A C 
CC A AC A
AC A C BA A
AC A B B CC A B 
A BB B C A BC BC CC A AC
A AC CC 
B B AA CB CC A C A A
AC A CC CC 
C C AB C BB B A AA A AC 
C C C B C CC C BA B A 
C B C C A CC BC AB AB AB 
CC B B AC A A BA AB A AA 
CC C CA CC A A
AC A B BA AB A C 
AC BC AC A CA A AC
A A CA BB CC B 
CA B C AC BC A B A B A 
C BB A BB B BA A C BC B 
B C A CA A A C BC B AA 
CB CC AB BA C B AB CA AB B 
BC B A A A B CB B B A 
A A B CB C AA A A B B 
C C A C CC CC CA C BC BC 
BC B CC C A BB BB B C C 
B BC AA A A AC
A B CC B C B C 
AB A
AC A A BC B A AC A CA BA A AC A
A
AC A AB 
CB CC AC A A B CA BC BC CC 
BC C AC AA C B CA BB A AA 
AC A AC
A BB BC A CB CB B B A A 
AA A BA CB B A AC A
CB A CB AB B 
AC AB BA A AB A BB B C BC 
AA AB BA CC A C AA C CA BB 
C CA CA C A AA B C CC B 
A A BB BC AC B CC BC A CA 
BC C B A
AC A AC AA A A AC
A AC A BB C 
A C CC BA CA C BA B C C 
BB A AC
A A CC A AC A
B A C C CA C A 
BA B CC CC AC AB C B B A
AC A CC 
B C A AB AA CC CB CC A AA 
A A AC A
A C BB BC B CB BA A A
AC A AB 
A CA AA C BC CB B C BA C 
B A AB C BB A BB AB AC C 
A BA BC CC B C A CA C B 
AA C B BC BB C A AC A
A AA A C 
A A BC BC BA C C BA A B 
CC A AC A
A AA BA AC CC A AC A
CA B C CB 
BA CC A A
AC A CC BA C CB B BB B 
C AC AC BA B AA A B BA B 
B BC BC A BC C BC BA A CC 
AA C C B C A AA A AB A
AC A AA 
B A C AB AA BA A C AB A 
AC B AB B C B A A AA A
AC A A 
B BC B C CC A AC
A AC AA A AC A 
C BA B BC AB CC B A A B 
BC B AC BA A A CB A C C 
BB A BB CB B CB BA AB BC AC 
C C CC B AA AB C B A C 
CA A BA C BA BB A AC C BA 
A C AA C B B C A B A AC A
BC 
BA C AB B BC AA C B B AA 
B A AC
A A AA C B BB C C BC C 
C BA A AC A
CB CA A CB BA AB C A 
CC BC AA BC BC CB B CB CB CA 
A A AC
A CC C CC BC A AC
A BA C CA BB B 
A C BC AB CA AB AB A C B 
A CC AC C A B BA AC CB A
AC A BB 
BA C C AA BC BC CC C C A 
AC C A AC A
C CC CC AB CA AB CC AC 
C AA A AC
A CA CC C B AC CC A AC 
B AA BA C B C B AC AB C 
CA A AC A
C BA AA AB A CC CC AA C 
C BA CC CC A BB CC C BA AB 
B A
AC A CC BA CB C A AC A
AC B C A C 
BC C A CA BC CC A BA C A AC
A C 
B C C A
AC A CC CC CA BA C BB AC 
B C CB AB C C BB C CB C 
B C B A C A B C C BC 
AB C C CC B AA B AB B CC 
CB C A C BA A A A AC
A A AC CB 
CA A AC C A AC C BC C C 
BC AC BC AB CC C CB AC BC B 
BB A
AC A BC B A AA AA B A AC
A B C CA 
AA BA AC BA AB BA CB CB B A 
BB B B BA A B C BC AC B 
AA A A C AC B BB A BC CB 
C A CB AC AA AC CC C BA C 
CC BC CA C B B AC BB CB A 
A A AC
A AC AA CB A B A
AC A A AC CC C 
C A CA A AA A AC A
A AB C A B 
AC BA A
AC A C BB BB CA C CC BC A 
CB A AC A
A BC B A B AA BB A B 
A A AC
A B A C B CA BB A BC BC 
AA C A BC BB A CB AB A A 
AC A AC A
AA C BB C BB C A C B 
B B CC C A BA A AC A
CB BA BA A 
A A AB A AC
A CB C A B BA A B 
BC BC AC BC C BB BC C B B 
AB BA C BA C A
AC A C A
AC A A CA BB B 
B BC B AB B BB B AB CA A 
CC A AC A
B B B BC B C B B CA 
AA A
AC A CB CA AC AA BA A AC A
C B A AC A
BC B 
C B A A C B CC C C B 
CC B A A BC BA C C A CA 
A A AB BB CB A B CA AC BA 
AC C AA AB AA C BA CC BA CB 
A A AC A
A B B CB A AA CC BB AA 
B C A A
AC A BC C A AC A
B CA BB BB B 
AC CA B B BB A A A C BA 
CC A
AC A A AC
A B B A BA C B A B A
AC A B 
BA C CB BC AB A AC
A AA CB A
AC A AA CA A AC A
AA 
B BB C AA AC C CB AB C A 
A BA A CC B BC CB AA C CB 
CC CC A A B BB C AA CB B 
B BA CA BB CB A AC
A BC B BC AA AA 
A A CC C AB BC C A AC
A B BA A 
B A
AC A BA CA A C BA A A AA A 
AB CA C A B AA CB C A A 
B BC C B CB AC BB A AC
A CB CC C 
A CC AB C B A C A B CC 
CA AC A BA B AC BB C C CC 
A CC AA C BB C CC AC A C 
C A
AC A B CC CA C B B C BA BB 
AA A AC
A B B CC C B AC AA B AA 
A AB C A AC A
AA B CC AC BC AB B 
A AC
A B AA BA BA BB C C A AC AA 
AB BA BB BC C BB B BC AA C 
A A AC A
A
AC A AC CB A A CB CA CC AC A 
A AC A
CA B C CA C A AC A
A
AC A CB AA BB BA C 
AC A A B BB A AC B BC CB 
C C C B A AC A
A B A BC C CC 
B BA B C C BC AB A AC
A C CC B 
B C AA BB CC B A C C BC 
C AC BB CB B A B BC B BC 
B C BA AB AB A CC AC A C 
B AB BA B BC A
AC A A BA A B C 
C A
AC A AA A AC B C BB B A C 
C BC A AC
A A AA B CB A AC CA CA 
B BB A A BA CA C CA BB CB 
A AA AA CB A CB C AC AC C 
BB C B A AC
A AC B AA AB CC B A 
A CA A A
AC A AB A C C AC CA BB 
AA A A AC A
A
AC A AA BB C A A BB BB CC 
AB A CA CA AA C B A CC CC 
CC AA B AA C AA A AC
A A A
AC A A AA C 
AA A
AC A AA BC BC CC B AC BC C CA 
B BA C AA BA B B BB C AB 
BC AA A BB BA B B B A AA 
AB CA B A A A A AA C B 
B A AC
A C BB AA AB CB C CB BC A 
B AC CC BA C BB A C A CC 
CB BC BA B C B CA A
AC A CC C BB 
BA BC B B BA CC C A BB CA 
C A BC AA CA C A C BB CA 
C BA CC BC C CB CB A A B 
C CA A CA AA C C A AC A
A
AC A CA CB BA 
CC A AC A
A
AC A CB B AB C BA B AB CA CB 
AA C C BC B BA AB CC A A AC A
B 
B B BC AC A AC AC AC AA AA 
B AA AC C AB B CB AC AC AA 
A BC BC B AA A AC
A AB BC BB A CA 
A C C B BA C B A AC C 
CC C BC CA A A AC
A CB A AC A
BB AC CB AA 
CC C C BB CB CB B A AC
A C BA BA 
B C AB C C A AC A
BC B A B BC 
BA C C BC C CB BA B AB BC 
CA B C CC B C AB B C C 
CB AC B A AC A AC A
BB CA AA A C 
CC B CC A B A
AC A A AC
A BC A AA BC A AC A
BB 
A A AB A C A BB BB CC A 
BB C B BB AC CC CA A C CA 
CC CB CA C C BA C C C CB 
A A
AC A A AC
A A CC BA A AC
A A B B C A BB 
CA B A C BA A A AC A
AA BB AB B 
BB CC A A CB CC BA C C CC 
CA C B CC CB B BC A AC
A BA A CA 
BC A AC A
C CC A CA A AC
A A A
AC A C A B B 
AB C CA CB B CA AB C CB C 
B A AC A
B BC CA AC AC C B B A
AC A B 
C CA CC A BA AB A AC A
A C A AA 
AC AA BA A CC CB A C CA CA 
B B C AA CB A B AB BC A 
AA A AC A
A AC
A B BB A A AA BC A
AC A B AC C 
B CB CB C AB B C BA CC B 
CB A A BA B CA BA B B CB 
A BB B C CC BC C C CA A AC A
AC 
AB CB AA A C A AC A
A AC
A AB AC B C B 
AA A AC A
CA AC A AC A
AB A BA B A
AC A B C BB 
A AB BA C BB C CC A AC A
A CA CC 
C CA AA CB BA A AA A A CA 
CC CB C A AC
A CC A A AB A A AC
A A A AC
A CA 
A AC A A AA BB B AA CB CB 
AB B AB C C BA CA B AC B 
BC A
AC A C C C C AA BA C BB A 
B A AC A
A AC
A A C C B BA B C A A 
C BC B A C CA AB BC BA C 
CA A A B A CC C C B AC 
AA AC C AA C A AC A
C C A
AC A CC A A 
CC BC AC AA A A AC A
C B BA A A AC A
BA 
B C CB CC A B B C A
AC A BB B 
A CC BC B B BC A AC AA CA 
B BC C CB C B C B BC B 
BA A AC A
A
AC A A CC B C A AC A
AA C A C BB 
A B BB AA B C A AC A
A A AC A
AA AA A 
CC BA B CA A A A B B BC 
C B CC A A CC B B A BB 
AA A BB AA AB C A
AC A AB CA AB A
AC A CB 
AC A A B BB BA A C B AC 
AB A B AC A A AC A
B C B CA A 
A AC A
B A AC A
BB CA CB C BC C CC A CB 
AA A C AA C C A C BB CA 
AB A
AC A C C B CC B C A BC B 
BC B A B B CC BA CA CC BA 
A AB CC B B C A CC BC C 
AC CB AA BC B C BA A A B 
B A CA B B BA BA B AC AA 
BB AA BC A A CB B BB CC C 
A B CA B BA A A B BA AA 
A C C C CB C A C AB B 
BB AC CB B C B AC C A AA 
A B C AA B C AC A AC
A C AB B 
BC CB C A AC A
B AC CB C C AB BC 
A CA C C A B B AB BC BC 
A A A AA C AB C CC C A 
BA C A AC B A A CC B C 
C A AC A
BC CC B BC A BC C AA C 
A A AC A
A
AC A A AC
A A A CA AA AB B B B AA 
CC A AA C CA CC AB A AA CC 
A AB A BB AB CA A
AC A A B CB B 
C B A CB A AC
A CB C A
AC A B A AC A
B BA C 
AC CB A B AB C BC A A B 
BB BB C BB BB BA CC A BA B 
A CA AA C C A CC CA BB BB 
C A CB A AC A
A
AC A CC C AA A
AC A A CC B AA 
CC C C A A BB CC CA C AA 
CC AB C CA A B A BC B AA 
BB BC BC AA BA AA CA A A B 
AA B AA C A C AA CA BB A 
C AA A
AC A A C BB BB B AA B C 
BC A C C BC BB AA BC B AB 
B BA BA BB BA A AC A
CA C CB B BA 
A A AC
A BB BA C B A AA C C CA 
C B BC B B BB A B AA BB 
A BA C A AC
A B A B AA CA C BB 
B A AC A
A AC
A AB BA BA CA AA BC BA A AC A
CA AC 
A AC
A C A CA A C C BB CA C A AC
A AB 
A C B BB C CA A C C A
AC A CA 
A C AB C AC CC AA CB BA BB 
C C A B BB A AA B CA AA 
B AC BA CB CC AA A B BA CA 
B C CA BA B AA B BC CA A 
B A AC
A AB AB B AB B C C A BB 
A B CB CB B A AC
A BB BA AB B CA 
CC A AC A
C C B BC AC BB C B A 
BA A
AC A B A AA C C C BC A AC A
BB A AC A
A
AC A AB 
A A A A A BB CC BA B A 
C AB BB AA CC B C CA AC AA 
BC BA A A AC A
B AB B B C CB BB 
B A CC AC C B A A B A 
BA BA A
AC A C AB CA C CA A C A 
BB A AC A
B BC A AC A
B CA A CC AC BB AC 
A C CB A
AC A A CA B BA B BA A 
C A AC A
CC CC A B AB C CA AC A AC A
A 
C AA AB B C B CC BC BC C 
B A AC A
A AC
A C CB CC A A AC
A B B CC C AB 
AA A C B BB BB CB A AC A
B AA A 
B AB BA B A CA A
AC A A A A BA 
B A C C AB BC BA B B CC 
C A B A CC C C A
AC A CC A AC 
A B AC BB AB A BA BB C B 
B A AC
A A CA A AC
A C CA BB A C A C 
A A AC A
C CB C C CC A B C CA 
A
AC A AB AA A AA C B AC CC A AB 
AA A B AB C CC CB AC AC CB 
A A
AC A A CC AA BB CA A A C A 
B A C A C A B A AC
A A B BA 
CC BB C B CA A AC
A B A C C BB 
BB BA A BC C B CC BA BA AA 
A A B A B AA B BB BC A AC
A B 
BC AC B AC AB AB A
AC A A A A BA 
B A C BC A AB BB A AB C 
B A C B A A BC BA B CC 
BC AC C B A A CB CA AC B 
A AC A
A C C BA AA C AA BA B A 
A CC A AA CA B B BC CB B 
C A
AC A CC CB BC BC A
AC A C A AC A B 
CB A AC A
A AA CB A A A AC A
A
AC A AB AC AB A AC
A C 
C BC CA A
AC A B B B CA B B CB 
A C CA CB C A
AC A AB CB B BC B 
CA A AC
A BB AC CC CC AB CC BC A AB 
A A
AC A B A B B AA CC B CC B 
A AC A
CB C C CB B B AB C C C 
BC A AC
A C A AA CB BB B A AC
A BB BA B 
BA C BA C A C BA A B AA 
A AC A AB C C A A AC
A C AA AA 
CB C AC BB B CA B BB A B 
A A B AB A C C C A CA 
AA B AB AC CB A A B CB B 
CC CB AB A C BB A B BA A AC A
AB 
CA CB BC A AC A
B C BC AC BC BA C 
A BC CB CB B AA B B C AB 
B AB CB AB CC AB C AA BA A 
AA BB C CA BB A BA BB AC CA 
C AB AA B CB A AC A
A
AC A A AC
A A A C B B 
AA A
AC A A AC
A C A AC A
CB AC AA A AA B A AB 
CB B BC A AC A
A AC
A C B A AB B BB CC 
CB B A AC A
A AC
A BA A AA AA BA CC C AB 
C A B BA B B CB BC BB BA 
B CB BA AA CC C A
AC A AB AC CA B 
CC BA AA AC BB BB BA C AA C 
B C C B CB AC AB CA BA B 
BB BA A AC
A B CB A BA C BC BA A
AC A CA 
BA A AC A
C BC CB A C A AB A BA 
B A BC A B C CB BB CC C 
A A AC
A A BB C B CC B A AC A
CC A AC 
B BC A
AC A AB CB C CB AA A CA A 
B A AC A
C C A A CA AA A A AC
A AB AA 
BC A
AC A C A AB BA AA BA A
AC A C C C 
CA CA BC AB A A
AC A C C AA A AC 
C AC CA B A
AC A C A BA C AC C 
CC CA B C BA CA CB CA CA A 
BC B C C AB C C A B C 
AA AB BB B A A A AB B C 
B A CC AC A A B BB BA AB 
CB AA CA C A AC
A C A AC
A AB CA CA C A
AC A C 
A AC
A AA CC CA B AA CB C BA BB BC 
BA A C AC A CC AA CA CA BA 
C B A B A BC AC AB A A AC
A CB 
CA BA B A BA AA B CA A A 
C A A CA BC A BB C AC CC 
BB C BC C C C A BB A
AC A A B 
BC A AC A
A
AC A BA AA C CC BC CC A
AC A A AC
A B C C 
B C CC C BA A BC AA C A AC
A BB 
A A A C A B C BC B AB 
BC A A BA AC CA A AB BA AB 
A AC
A CC BA C BB A BA CA B A AC 
B C BA AA BC B B C A AC
A BA AA 
C A AC A
A AC
A AA C B CB BC BC C CB C 
CA A AC
A C AC CA AA BA BC B B A 
B AA C A BB B CA A A BA 
CA A AC
A BC A AC A
A AC
A BC A BC C C C C C 
CB BA C A BB CB BA C B C 
B CA C A C A B BA B B 
AC C BB B A C B A B A 
AA C CB AB B B A AA B A 
A CC AC BC AA A
AC A CB BB B AA A AC A
CB 
B CA C AC A B BB C B BA 
A B B CC AA B B A CC A 
C CB A AC A
B BA BB AC BB AA B CA 
C B AA AB B B BB CC BA AB 
AC B C A A CB BA AB AC B 
A A AB C A A CC C B B 
CC AA B C BA C C BC A C 
A B B BB B BB BB C BC B 
A A AC A
A C AC A C A CC AC CC 
BB BB BA BA A B AB AB C C 
A AC A
A CB C B C C BA A BC AA 
CB B B A BB A
AC A C B A B C 
CC A AC A
A AC
A AB A C C A BA C AC A
AC A BC 
A C C CB C A C C CB C 
AC B A CA A A C C BA A 
CB CA BA A
AC A CB C C AB CA B AA 
AB A
AC A BA BC BA B A
AC A BB A CB BC B 
C AA C CB C AB B AC BB BA 
C A AC
A A C A C B C BB CB B 
C CC CA CB C BC C BC B AB 
C CB A B AC A AC A
A
AC A A AC
A A C BB B A AC
A BB 
AA AB B A C AB C B AC CB 
BA A A A B CA CA AA A A 
A BA CC A C AA BA C C B 
A A AC
A AA C C BB C A A
AC A BB B CB 
CB AC CA A
AC A CA C CB B CA AC C 
A A
AC A A AC
A B AB CB C BC AA A AC A
BB A A 
AC CB CA B C C CB CC CA AB 
CA A
AC A A CB A AA BA C C BA C 
C CC BA CC AB A AB BB A A
AC A BC 
C A BB CC A A
AC A A AC
A A B CC C A 
A A
AC A C BB AB A C BC A C B 
A A AC A
B A AC A
AC A B AC A CB B B 
CB A AC A
A AC
A BA AB CB B AB C A AB B 
AB B BC CC B A AC B BC AB 
BA A C C AC BC C B A A
AC A BA 
A AC AB CA AC A BB BC C CB 
A B AC C A AB AA C A C 
B BA A B BC A AC A
A
AC A C BB CA C CC 
A AB A AA BA C B AB A
AC A BC B 
AC B A CC CC BC BB BC BC A 
C CA A A B A
AC A BC B BB BA BA 
AA C BA B AB BB A BC CC C 
A AA B B BB CC BB A BB A AC A
B 
CA BA A B BA C BA C BC A 
CB A AC A
A
AC A CB A C B C BA A
AC A CA A C 
CB B CC CA AA AC CB AB CC A 
CA AB AB AC A AC A
BC BC BB CB C CC 
BC A AC A
B A B BA C A CC A AC
A A C 
CB A A C CC C B BA B C 
CC BB CB BA AC C BA A A B 
B A
AC A A A CB C C C B CB BA 
A AC
A A CA C AC B B B A AC A
BC AA B 
BC A AC
A A A C BC AA C C C BA 
AC A AC A
B A CA A AB AB CC C A 
B B C A
AC A AA AA A CA CC BB AB 
AB A B A BB CC A C B B 
C B B B C B B B BA A 
C A CB A AC A
CC A CC BA A BB C 
A B A AC
A C BA C B BA A AB A AC
A CA 
AC C C B A A AC
A BA AA B AC C 
B BA C AB AB B BA BB B B 
CB C C B A A AC A
BA AB CC A BC 
AA A CC B AB BC AB AA C A 
B C C B B A CA B B B 
AC BB BC BA B C AA C B C 
BC BA CB B AA C B A AC
A AB C A 
A A B A AC
A AB AB CA B C AA B 
AA A AC A
A B AB CC A AC
A BB AC B CA CB 
C AA CA C B C BB B BC CA 
B C B B CA AC C AA C B 
C A AC
A C A AC A
B A B B B CA A B 
A A AC A
A
AC A C A C C AA AB B AB C 
C C CA BB CB CB CB C AA CA 
A A AC A
A C BC B A BB B AA AB 
AC A AC
A AA AC A B AB AC B CA CA 
B A A A
AC A C C BB CA BC CC A
AC A A AC
A CB 
CA CC C AA BA B A BB CB A 
C A AC A
CB A AA B B B A AC
A C AB C 
AB BB BA AC A C BA CA AC A AC
A AC 
CA A A A AC A
B AB C AC CA BC C 
BB BB BC AC AA BB AC B A AC 
CB AA A AA AA A AC A
AB CA CB B B 
CA B A CC A CC A AC
A C CB C CA 
C CC C CA B CC CC C BB A 
CC A BC AA A A B A C B 
B A CB B CB B C BB BA CC 
CB C AC B C BA AA BC B AC 
