import string


str1 = "IQZIZIQQQFZIZZQZFGZQQFQIZGQFIQFIGIFFZQZQIIQFFGQFFZQZFIFFZGIGQIZFZGIIIGIQFZQFQFQZIIFFGQFZZGFGGFZIIFIZQQQIQIZZFGGZGFZFFZFQFIFZIGIQFGQZIQZZIGGFFGFFIIIQFGZZFZZQGFZFQIGQQIZFFFIQGQFGFQGQGZIZFIIZFQZZFGFGIGZIGFZGZZGGQGIQIZGIQZFGGIGGIZGQZGFFZGQQIQIZQZZIZGIIIGZZQFZQ"
str2 = "PFNDKNSNDFKSCMCIKSDGNSNNJSKFNSDGKFGNKSNGKFBKGBKDFKNVBDKFVKSDBJKHGKDFHGVKFGLFFDHFDHFJDKFJGKFJGFJTJKJBKLDTJKJGJRFJFKMGKGFJGBKLFMLKRYJRKKYTLMYKYMKTMYKTKLYMTKLMLKRMFKMFLTKYKLTMYKTMFKYRLKTRMYLKLMGLKMKTYKLTMYLMLMHLMTFLKMYTKYMKTYKLMYKTMYLKYMLKMKLMYTLKMTYLUMLTMTKY"
str3 = "JFDKGJFDKGJKDJGKFJKGNFKNGLKDJGKFDNGKDFNKGJNDFKJGNFDKJNGDKJFNBKFNHKLFNDGKNFDKHMFLKBMGBMNFNGKLFDMHNGKDFKLNGMULDFKUGYNLDFKNNKGFDHTDNHDFMNDHGBKFDMFDFBCFNJGDFKNGFDKGJKFDKJBNFDJGNFKNGKDFNGKFGKJDFKGJFDKGJKFGLFDJGKLFJGLKFDLGKDFJDLKMDFLKDFJHLKJJLKFDFDJJKDFLJGKJFDKG"
str4 = "GFKGJFKLGKLFDGLFKDXLMGKLXMKLFCMKDXKGNFCBCVMFLKGJDFKLGMLKGMDKLMGKLDNGKJDNGLMFMHKFMDLGJKRJIJGRDNGKJDRNGFDJKGFDKGKFLDNHKJDFNHKJFNKFNHFKHFKLNHFLKHNGFKNHFKNHDKFBNDKHNKDHFNHKNDFKFHDNFHGLHFNHKDFDFLKHNGHNKHDLHKJIDHJRDNMKHJGJGFJJHJHDTNKKDJDHKJDHIJDMRGDNKDGJJFDGIOJR"
str5 = "KFDOJGOKDFJGNDFKJGNKJFDGKDFKGJFJKNGFMCGBMFVCFBNFKJGNFDKJNGJFMNGBKFMNGKDFNGKJNFDJGNDFGNDFGBMFDLKHMKLDFHLKGDMLKHGFHMKLFHNHFKNHFKLFNLFHKHFNGFKLHNKLHGNKLGHKGFNFKGNFKGBLNKFBMLGKHMKLFGHNMGFLHMFGKLHNKGFMGMNLMGFLKGMKGMHMKMKFGNKBKNFGGFNBFKNKGGFKLGBKLFGNKFGNLFKHNKGF"
str6 = "FLVGMFXKMFKLDMGKFMGKFDMGKMDFLGMRLFDRMGKRMFKLMVKFBNKFDNGNDGLKFKGMFDLKGMDFLKGKLFDMGLKFDNKGLFDKLGFDKGNLFDNGFKGNFLKDGNKFDNKDNKGFLNBKGNGFBKGFKGBFKLGFBLKLGBFKGFBKNLGDBKLDBKLDGBKLDGBKLBDKLFBDKMDFBKFKLDBKFDBMLDGBMBDFLDBLBLKDBMKDBBDMDFMDBFBDMFTFKYEUJRJIERYFGHGFGFDF"
str7 = "CFGNJHFGKNDKNGKDJNFKJDNKJFNDJFDKMFVDNXLFKJDSJFLKDMFKMDLKFDLKFDLJGKDJFGKDNMFLKNGDRGUJHDJGBDJNRFJDGBJDFGJFNGKFNDGJKNDFJKGNJKDFHGJKFGJDFNGKJNDTJKGJFKNGKNFDGHKGFHFGNHJKFTHJKFNGHDKJFNBGFNFGKJNFGNKDHFNKFNKTFHJTIHFIHRNRJDFNKNFDKJFNLNGBNGDKRRHKFNGDKNFNDHFNKFKFHDNJ"
str8 = "DJGDFJJDGNJKERFJREFNKLSDFNMLDKFNMKMDSKFJREKFKLNDKSFNDKNGFKLDNGKNFKJGNDFKNGKFNGDKNRGRKNDFKNGKDFNGHFNHKLDFKFHLKLHDKLFKGKMHDKNDGKLGHKLGDNKFKFNKLFGLNKFNKRDGJFSFDJIOGJRFDJGFGDFKNGKJFGJKFNDGKJNDFKJGSDKGFJDKNJDFNDNVCMNVKDNFKDSJGJSDKGVDJGLKJDFKNBDJNVJBNFDKNNBFDNNK"

with open("testmany.txt", "w") as out:
    for a in range(len(str1)):
        out.write("+ {0} 0\n".format(str1[:a+1]))
    for a in range(len(str5)):
        out.write("+ {0} 0\n".format(str5[:1+a]))

    for a in range(len(str2)):
        out.write("+ {0} 0 \n".format(str2[:a+1]))
    for a in range(len(str6)):
        out.write("+ {0} 0\n".format(str6[:1+a]))

    for a in range(len(str3)):
        out.write("+ {0} 0 \n".format(str3[:a+1]))
    for a in range(len(str7)):
        out.write("+ {0} 0\n".format(str7[:1+a]))

    for a in range(len(str4)):
        out.write("+ {0} 0 \n".format(str4[:a+1]))
    for a in range(len(str8)):
        out.write("+ {0} 0\n".format(str8[:1+a]))

    for a in range(len(str1)):
        out.write("{0}\n".format(str1[:a+1]))

    for a in range(len(str2)):
        out.write("{0}\n".format(str2[:a+1]))
    
    for a in range(len(str3)):
        out.write("{0} \n".format(str3[:a+1]))
    
    for a in range(len(str4)):
        out.write("{0}\n".format(str4[:a+1]))

    for a in range(len(str5)):
        out.write("{0} \n".format(str5[:a+1]))

    for a in range(len(str6)):
        out.write("{0}\n".format(str6[:a+1]))

    for a in range(len(str7)):
        out.write("{0}\n".format(str7[:a+1]))

    for a in range(len(str8)):
        out.write("{0}\n".format(str8[:a+1]))

    for a in range(len(str1)):
        out.write("- {0}\n".format(str1[:a+1]))

    for a in range(len(str2)):
        out.write("- {0}\n".format(str2[:a+1]))
    
    for a in range(len(str3)):
        out.write("- {0} \n".format(str3[:a+1]))
    
    for a in range(len(str4)):
        out.write("- {0}\n".format(str4[:a+1]))

    for a in range(len(str5)):
        out.write("- {0} \n".format(str5[:a+1]))

    for a in range(len(str6)):
        out.write("- {0}\n".format(str6[:a+1]))

    for a in range(len(str7)):
        out.write("- {0}\n".format(str7[:a+1]))

    for a in range(len(str8)):
        out.write("- {0}\n".format(str8[:a+1]))

